#!/bin/bash

# Fetch the Instance ID of the only running instance
INSTANCE_ID=$(aws ec2 describe-instances --filters "Name=instance-state-name,Values=running" --query "Reservations[0].Instances[0].InstanceId" --region ap-south-1 --output text)

# Fetch the Public IP of the instance using the Instance ID
PUBLIC_IP=$(aws ec2 describe-instances --instance-ids "$INSTANCE_ID" --query "Reservations[0].Instances[0].PublicIpAddress" --region ap-south-1 --output text)

# Output the Public IP
#echo "Public IP of the instance: $PUBLIC_IP"
ssh -vvv root@$PUBLIC_IP -i ~/.ssh/ec2
